### ISSUE TITLE
Versión HTML multipágina

### ISSUE THREAD

**Issue by aplatanado** [ull-esit-sistemas-operativos/ssoo-apuntes#4]
Asciidoctor no admite salida HTML5 multipágina (una por capítulo, por ejemplo).
La conclusión de https://github.com/asciidoctor/asciidoctor/issues/626 es que no piensa incluirse en el core.

Hay un conversor desarrollador como un proyecto aparte pero no funciona con la versión 2.0

https://github.com/owenh000/asciidoctor-multipage/issues/2

Tampoco estoy seguro del a ventaja hasta ver si tarda mucho en cargar.
Hay que valorarlo

**Comment by wshito** [comment]
@aplatanado  I released the [asciidoctor-chunker](https://github.com/wshito/asciidoctor-chunker) which converts the single html generated with asciidoctor into chunked html keeping the structure and design as it is.  It is written in JavaScript and super easy to install.  It's just a single bundled script and runs with NodeJS.  Here is [the latest release.](https://github.com/wshito/asciidoctor-chunker/releases/latest)  

The depth of extraction can be as deep as asciidoctor's maximum subsection level. And you can also control the depth of extraction in each chapter if you want.  The footnotes are supported.  I hope it helps your project.

I haven't finished the cosmetic part of the page navigation. The help is always welcome. If it is too much hassle to write a code, you can send me an additional CSS and I can always put that into the code. Or maybe I can add a theme support.

Feedback is always welcome. Feel free to request the enhancement.

**Comment by aplatanado** [comment]
@wshito thank you for your recommendation. I will try it when I can.
