### ISSUE TITLE
Cambiar a alternativa libre de disqus para los comentarios

### ISSUE THREAD

**Issue by jesustorresdev** [ull-esit-sistemas-operativos/ssoo-apuntes#58]
Se puede usar:

https://utteranc.es/

**Comment by aplatanado** [comment]
giscus usa las discusiones de GitHub, por lo que puede ser más interesante:

https://giscus.app/es
https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md

El problema es modificar el actua para que use esto en lugar de disqus.

**Comment by jesustorresdev** [comment]
Hasta el momento nadie ha usado los comentarios. No parecen ser muy útiles
Quizás no deberíamos invertir tiempo en esto.
